version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
        command: ['npm', 'run', 'start']

    tests:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - app
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        command: ['npx', 'playwright', 'test']
